#!/usr/bin/env python

__author__ = "Jon Dawson"
__copyright__ = "Copyright 2010, Jonathan P Dawson"
__license__ = "MIT"
__version__ = "0.1.3"
__maintainer__ = "Jon Dawson"
__email__ = "chips@jondawson.org.uk"
__status__ = "Prototype"

import sys
import compiler
import chips

def show_help_message():
    print """
chips_sim
==========

chips to vhdl converter.

usage
-----

chips2vhdl <input_file>

	--help          Print this help message

	--version       print versions

"""
    exit(0)

mode = "simulation"

for arg in sys.argv[1:]:
    if arg == "--help":
        show_help_message()
    elif arg == "--tree":
        mode = "tree"
    elif arg == "--version":
        print "chips version:", chips.__version__
        exit(0)
    else:
        input_file = arg

if mode == "simulation":

    input_file = open(input_file, 'r')
    input_file = input_file.read()
    parser = compiler.Parser()
    chip = parser.parse(input_file)
    chip.reset()
    chip.execute(1000000)

elif mode == "tree":

    input_file = open(input_file, 'r')
    input_file = input_file.read()
    parser = compiler.Parser()
    chip = parser.parse(input_file)
    print chip

else:
    show_help_message()


