#!/usr/bin/env python

__author__ = "Jon Dawson"
__copyright__ = "Copyright 2010, Jonathan P Dawson"
__license__ = "MIT"
__version__ = "0.1.3"
__maintainer__ = "Jon Dawson"
__email__ = "chips@jondawson.org.uk"
__status__ = "Prototype"

import sys
import compiler.parser as parser

input_file = sys.argv[1]
input_file = open(input_file, 'r')
input_file = input_file.read()
theparser = parser.Parser()
theparser.parse(input_file)

