#!/usr/bin/env python

import sys

import compiler.parser as parser
import compiler.optimizer as optimizer
import simulator.simulator as simulator
import assembler.assembler as assembler

input_file = open(sys.argv[1], 'r')
input_file = input_file.read()
theparser = parser.Parser()
instructions = theparser.parse(input_file).generate_code()
instructions = optimizer.optimize(instructions)
instructions = assembler.assemble(instructions)
simulator = simulator.Simulator(instructions)

while simulator.program_counter != 3:
    simulator.execute()
